### PR TITLE
ci: npm publish on CI

### LINKED ISSUE #1593: Enable NPM publish again
Revert this commit to do so:
https://github.com/hirosystems/stacks-blockchain-api/commit/b56cc82144e9fc33ffaf565e3f9a5ef0e57c0120

However, [there may be build failures](https://github.com/hirosystems/stacks-blockchain-api/actions/runs/4493354066/jobs/7904566509).

### PR DESCRIPTION
**Pull request by csgui**
This PR fixes #1593 

An update of the `rimraf` external library was checked and validated.

### CODE REVIEW

**Review by CharlieC3 — APPROVED** [review]
LGTM! :shipit:

**Review by rafaelcr — APPROVED** [review]
LGTM! Thanks @csgui

**Review by zone117x — APPROVED** [review]
Thanks @csgui! ~~Before merging, can you rebase onto `develop`? Otherwise the diff is pretty messy and will include a bunch of stuff that looks like a merge from master to develop.~~

EDIT: nvm, looks like this one is good to go!

**Comment by csgui** [comment]
@zone117x @rafaelcr and I was talking about that right now! You read our mind, sir! :-)

**Pull request merged**
