### PR TITLE
feat: add prometheus metrics for websockets

### LINKED ISSUE #840: Add prometheus metrics for websockets
We currently have custom prometheus metrics in place for socket.io (from #731 ) that measure channel usage, total connections, disconnections, etc. We should add similar metrics to websocket usage so we can monitor how our users are interacting with them.

### PR DESCRIPTION
**Pull request by rafaelcr**
## Description

This patch adds Prometheus metrics for WebSocket usage. Example:
```
# HELP websocket_subscriptions Current subscriptions
# TYPE websocket_subscriptions gauge
websocket_subscriptions{topic="block"} 0

# HELP websocket_subscription_timers Subscription timers
# TYPE websocket_subscription_timers histogram
websocket_subscription_timers_bucket{le="1",topic="block"} 0
websocket_subscription_timers_bucket{le="5",topic="block"} 0
websocket_subscription_timers_bucket{le="10",topic="block"} 0
websocket_subscription_timers_bucket{le="30",topic="block"} 1
websocket_subscription_timers_bucket{le="60",topic="block"} 1
websocket_subscription_timers_bucket{le="180",topic="block"} 1
websocket_subscription_timers_bucket{le="300",topic="block"} 1
websocket_subscription_timers_bucket{le="600",topic="block"} 1
websocket_subscription_timers_bucket{le="1200",topic="block"} 1
websocket_subscription_timers_bucket{le="1800",topic="block"} 1
websocket_subscription_timers_bucket{le="3600",topic="block"} 1
websocket_subscription_timers_bucket{le="+Inf",topic="block"} 1
websocket_subscription_timers_sum{topic="block"} 10.78
websocket_subscription_timers_count{topic="block"} 1

# HELP websocket_connect_total Total count of connection requests
# TYPE websocket_connect_total counter
websocket_connect_total 1

# HELP websocket_connect_remote_address_total Total count of connection requests by remote address
# TYPE websocket_connect_remote_address_total counter
websocket_connect_remote_address_total{remoteAddress="127.0.0.1"} 1

# HELP websocket_disconnect_total Total count of disconnections
# TYPE websocket_disconnect_total counter
websocket_disconnect_total 1

# HELP websocket_events_sent Total count of sent events
# TYPE websocket_events_sent counter
websocket_events_sent{event="block"} 10
```

Closes #840 

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] API reference/documentation update
- [x] Other

## Does this introduce a breaking change?
No

## Are documentation updates required?
No

## Testing information
Local testing

## Checklist
- [x] Code is commented where needed
- [ ] Unit test coverage for new or modified code paths
- [x] `npm run test` passes
- [ ] Changelog is updated
- [x] Tag 1 of @kyranjamie or @zone117x for review

### CODE REVIEW

**Comment by CharlieC3** [comment]
Nice addition! What are you thoughts on adding a couple more metrics below?

* A bucket denoting the time a websocket spent connected. This would be useful to get a histogram defining the 25th/50th/75th/95th/99th percentiles of how long users are connected to the API via websockets.
* A counter tracking the number of websocket connections opened per source IP. I'm skeptical about this one since it may have to track so many different IPs that it'll hit the same problem the URL metric hit, which lead us to grouping the URLs together under different high-level umbrella paths. But it could be useful to have. Might be worth testing in a canary.

cc @wileyj for additional thoughts on the above

**Comment by rafaelcr** [comment]
@CharlieC3 great suggestions... I'll start by adding the socket histograms while we discuss the IP counters

**Review by zone117x — APPROVED** [review]
LGTM!

**Review by CharlieC3 — APPROVED** [review]
:shipit: LGTM! The number of IPs counted in the metrics are very manageable, so I'm not concerned.

**Pull request merged**
