### PR TITLE
added note for mempool endpoints to clarify consistency gurantees

### PR DESCRIPTION
**Pull request by trichards-hiro**
Use the following template to create your pull request

## Description

A clarification was needed to explicitly state that data from mempool endpoints are not guaranteed.

1. Several Discord users noted that STX transactions were impacted by data from mempool endpoints not being guaranteed.
2. Added a note to all mempool endpoints in the openapi.yaml file

### CODE REVIEW

**Review by zone117x — CHANGES_REQUESTED** [review]
Can you also add the comment to the `/extended/v1/address/{address}/mempool` endpoint?

**Comment by trichards-hiro** [comment]
@zone117x I went ahead and added the note to the one endpoint I missed. Thank you for the good catch.

**Review by zone117x — COMMENTED** [review]
Can we hold off on this PR until we see if https://github.com/hirosystems/stacks-blockchain-api/pull/1561 gets rid of the underlying problem that prompted this doc change?

**Comment by trichards-hiro** [comment]
@zone117x Sure....I can hold off until we know whether the fix you are working on resolves this issue.

**Pull request closed without merging**
