### PR TITLE
feat: use primary pg server for notifier

### PR DESCRIPTION
**Pull request by rafaelcr**
Adds primary pg server .env vars for `PgNotifier` to use.
Related to #990

### CODE REVIEW

**Review by zone117x — APPROVED** [review]
This looks good to me. I think we'd need to add more docs around usage if/when other parties would want to use this feature, since the pg replica setup needs to be setup in particular away to ensure they are synced for the sql queries that follow a NOTIFY.

But we can add that later if needed.

**Comment by rafaelcr** [comment]
Thanks, I agree @zone117x that's a good point... maybe I could expand the .env comments a bit to mention this if @CharlieC3 has a good basic suggestion for replica setup

**Comment by CharlieC3** [comment]
@rafaelcr There's a few required settings in both the primary and read-replica's configs that will allow for synchronous replication. Below are some trimmed down snippets for both a primary and its single replica. If a db cluster has more than 1 replica, it would only have to change slightly.

Primary config snippet:
```
#------------------------------------------------------------------------------
# CONNECTIONS AND AUTHENTICATION
#------------------------------------------------------------------------------

listen_addresses = '*'
port = '5432'

#------------------------------------------------------------------------------
# WRITE-AHEAD LOG
#------------------------------------------------------------------------------

wal_level = 'replica'
fsync = 'on'
synchronous_commit = 'on'

#------------------------------------------------------------------------------
# REPLICATION
#------------------------------------------------------------------------------

synchronous_standby_names = '1 ("stacks_node_api")'
hot_standby = 'on'
```

Replica config snippet:
```
#------------------------------------------------------------------------------
# CONNECTIONS AND AUTHENTICATION
#------------------------------------------------------------------------------

listen_addresses = '*'
port = '5432'

#------------------------------------------------------------------------------
# WRITE-AHEAD LOG
#------------------------------------------------------------------------------

wal_level = 'replica'
fsync = 'on'

#------------------------------------------------------------------------------
# REPLICATION
#------------------------------------------------------------------------------

primary_conninfo = 'host=<PRIMARY HOST NAME> port=5432 user=<MY REPLICATION USER> password=<MY_PASSWORD> application_name=stacks_node_api'
promote_trigger_file = '/tmp/postgresql.trigger.5432'
hot_standby = 'on'
```

These configs don't include _everything_, like authentication settings or tunings, we should refer devs to the postgres docs and [PGTune](https://pgtune.leopard.in.ua/) for that.

**Comment by aulneau** [comment]
I've got this running and seems to be working well, thanks so much @rafaelcr :~)

**Pull request merged**
