### PR TITLE
Test Rosetta- network options api

### PR DESCRIPTION
**Pull request by LakshmiLavanyaKasturi**
Added examples for Rosetta network options in the OpenAPI.yaml. Testing with one example.

### CODE REVIEW

**Comment by LakshmiLavanyaKasturi** [comment]
@rafaelcr: Can you please confirm if the syntax for adding an example for Rosetta API is correct? Then I can go ahead and add examples for other API's as well. Thanks!

**Comment by rafaelcr** [comment]
@LakshmiLavanyaKasturi I don't believe Rosetta allows for a `page` query string parameter... most of its input comes from the POST body, see the docs here for some examples: https://www.rosetta-api.org/docs/AccountApi.html

**Comment by LakshmiLavanyaKasturi** [comment]
> LGTM, but can you fix the whitespace/formatting in the JSON file?

Yes, I will fix it. Thanks!

**Comment by LakshmiLavanyaKasturi** [comment]
@rafaelcr: Looks good now?

**Comment by LakshmiLavanyaKasturi** [comment]
@rafaelcr: Is this PR good to go?

**Review by rafaelcr — APPROVED** [review]
Thanks @LakshmiLavanyaKasturi !

**Pull request merged**
